name: Bug report
description: Report a bug
title: 'bug: '
labels: [bug]
body:
  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: Include logs and expected vs actual behavior.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: input
    id: node
    attributes:
      label: Node.js version
      placeholder: e.g. 20.11.1
    validations:
      required: false
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: e.g. Windows 11
    validations:
      required: false
